### ISSUE TITLE
Error socketio.exceptions.BadNamespaceError: / is not a connected namespace.

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-socket-client-python#1]
Loving this
able to use python to control npx without any env besides nodejs

please share where are the docs for the python client
im having issues setting icon to a group
```
>>> client.setGroupIconByUrl(g,"https://freesvg.org/img/1534129544.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/magic/.local/lib/python3.8/site-packages/wa_automate_socket_client/__init__.py", line 68, in __call__
    return client.io.call(item, {'args': args})
  File "/home/magic/.local/lib/python3.8/site-packages/socketio/client.py", line 468, in call
    self.emit(event, data=data, namespace=namespace,
  File "/home/magic/.local/lib/python3.8/site-packages/socketio/client.py", line 393, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
```

Thx a lot! :)

**Comment by mrodal** [comment]
Hey! glad you like it!

Did you manage to run any commands beside setGroupIconByUrl? is this the only method that gives you problems?

**Comment by fire17** [comment]
hi yes it was my fault,
i exited the wa server and reopened, rerunning this line made it work flawlessly (so far :P )
```
>>> client = SocketClient('http://localhost:8085/', secret)
>>> client.setGroupIconByUrl(g,"https://freesvg.org/img/1534129544.png")
200
```
