### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by moha-abdi** [open-wa/wa-automate-socket-client-python#4]
AFTER I RUN THE CODE WHICH IS THE SIMPLE CODE GIVEN IN THIS REPOSITORY I AM RECIEVING THIS ERROR:

Traceback (most recent call last):
File "/home/moha/PycharmProjects/wapy/firsmo.py", line 5, in
client = SocketClient('http://localhost:8085/', 'secure_api_key')
File "/home/moha/.local/lib/python3.10/site-packages/wa_automate_socket_client/init.py", line 43, in init
self.io.connect(self.url, auth={'apiKey': api_key})
TypeError: Client.connect() got an unexpected keyword argument 'auth'

**Comment by smashah** [comment]
Don't spam issues. This is your last and only warning.
